---
name: Next.js CI
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    lint-and-format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18.x
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Run ESLint
              run: yarn lint --fix
            - name: Run Prettier
              run: yarn format
